dataset:
  name: aptos-ddr
  root_aptos: data/aptos
  root_ddr: data/DDR
  img_size: 224
  
model:
  model_name: 'resnet34'
  compile: false
  lr: 0.01
  optimizer_algo: adamw
  loss_type: CE
  weight_decay: 0.05

batch_size: 5000
max_epochs: 500
seed: 42

project_name: Aptos-GNN
tag: BASELINE
