program: src/drgnet/scripts/train.py
method: bayes
metric:
  name: val_kappa
  goal: maximize
parameters:
  model.lr:
    min: 0.00001
    max: 0.05
  model.weight_decay:
    min: 0.000001
    max: 0.05
  model.optimizer:
    values: [adam, sgd, adamw]
  model.gnn_hidden_dim:
    min: 16
    max: 128
    distribution: int_uniform
  model.num_layers:
    min: 2
    max: 10
    distribution: int_uniform
  model.sortpool_k:
    min: 8
    max: 128
    distribution: int_uniform
  dataset.distance_sigma_px:
    min: 5.0
    max: 100.0
    distribution: uniform

early_terminate:
  type: hyperband
  min_iter: 5
command:
  - ${interpreter}
  - ${program}
  - "--config"
  - "configs/ddr_aptos_lesions.yaml"
  - ${args}
