dataset:
  name: aptos-ddr
  root_aptos: data/aptos
  root_ddr: data/DDR
  split: [0.8, 0.2]
  which_features: encoder
  feature_layer: 4
  distance_sigma_px: 10.188926358566473
  reinterpolation: [512, 512]

model:
  name: DRGNet
  gnn_hidden_dim: 128
  num_layers: 2
  sortpool_k: 74
  conv_hidden_dims: [64, 64]
  compile: false
  optimizer:
    lr: 0.023809590039981624
    algo: adamw
    loss_type: CE
    weight_decay: 0.03128685798976109

batch_size: 5000
max_epochs: 500
seed: 42

project_name: Aptos-GNN
tag: LESIONS
