dataset:
  name: aptos-ddr
  root_aptos: data/aptos
  root_ddr: data/DDR
  split: [0.8, 0.2]
  which_features: encoder
  feature_layer: 4
  distance_sigma_px: 8
  reinterpolation: [512, 512]

model:
  gnn_hidden_dim: 256
  num_layers: 4
  sortpool_k: 128
  conv_hidden_dims: [256, 128]
  compile: false
  lr: 0.005
  optimizer_algo: adamw
  loss_type: CE
  weight_decay: 0.05

batch_size: 1024
max_epochs: 500
seed: 42

project_name: Aptos-GNN
tag: LESIONS
